easy_admin:
    design:
        # these custom templates are applied to all entities
        
    entities:
      #  List the entity class name you want to manage
      User:
        class: App\Entity\User
        
    
      Produit:
        class: App\Entity\Produit
        

      Categorie:
        class: App\Entity\Categorie
        form:
          fields:
            - { property : "name" }
        list:
          actions:
            - {name: 'edit' , icon: 'pencil' , label: false , css_class: 'btn btn-secondary'}
            - {name: 'delete' , icon: 'trash' , label: false , css_class: 'btn btn-danger'}


